batch_size: 512
epochs: 40
lr: 0.002

device: cuda:0
num_workers: 4
seed: 1234
use_wandb: True

data_dir: data
out_dir: /content/drive/MyDrive/Colab Notebooks/DLBasics2024_colab/final/wavelet

# Evaluation
model_path: 